# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/qt-designer/foxync.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.setWindowModality(QtCore.Qt.WindowModal)
        main_window.resize(800, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_window.sizePolicy().hasHeightForWidth())
        main_window.setSizePolicy(sizePolicy)
        main_window.setMinimumSize(QtCore.QSize(800, 700))
        main_window.setMaximumSize(QtCore.QSize(800, 700))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(116, 27, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 27, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 44, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        main_window.setPalette(palette)
        main_window.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        main_window.setWindowOpacity(1.0)
        main_window.setStyleSheet("")
        main_window.setWindowFilePath("")
        main_window.setIconSize(QtCore.QSize(24, 24))
        main_window.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        main_window.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.list_devices = QtWidgets.QListWidget(self.centralwidget)
        self.list_devices.setGeometry(QtCore.QRect(20, 91, 361, 342))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.list_devices.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.list_devices.setFont(font)
        self.list_devices.setStyleSheet("QListWidget {\n"
"    border: 2px solid transparent;\n"
"    border-radius: 5px;\n"
"    background-color:  rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QListWidget::item{\n"
"    height: 40px;\n"
"}\n"
"\n"
"QListWidget::item:selected{\n"
"    background-color: #8D80AD; \n"
"     border-radius: 5px;\n"
"color:white;\n"
"}\n"
"")
        self.list_devices.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_devices.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.list_devices.setViewMode(QtWidgets.QListView.ListMode)
        self.list_devices.setObjectName("list_devices")
        self.buttonicon_options = QtWidgets.QToolButton(self.centralwidget)
        self.buttonicon_options.setGeometry(QtCore.QRect(690, 12, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.buttonicon_options.setFont(font)
        self.buttonicon_options.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.buttonicon_options.setStyleSheet("QToolButton {\n"
"background-color: transparent;\n"
"border: none;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"background-color: rgba(255, 255, 255, 0.4);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/ui/qt-designer/../medias/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonicon_options.setIcon(icon)
        self.buttonicon_options.setIconSize(QtCore.QSize(24, 24))
        self.buttonicon_options.setObjectName("buttonicon_options")
        self.buttonicon_about = QtWidgets.QToolButton(self.centralwidget)
        self.buttonicon_about.setGeometry(QtCore.QRect(740, 12, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.buttonicon_about.setFont(font)
        self.buttonicon_about.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.buttonicon_about.setStyleSheet("QToolButton {\n"
"background-color: transparent;\n"
"border: none;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"background-color: rgba(255, 255, 255, 0.4);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("src/ui/qt-designer/../medias/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonicon_about.setIcon(icon1)
        self.buttonicon_about.setIconSize(QtCore.QSize(24, 24))
        self.buttonicon_about.setObjectName("buttonicon_about")
        self.label_state_device = QtWidgets.QLabel(self.centralwidget)
        self.label_state_device.setGeometry(QtCore.QRect(689, 661, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.label_state_device.setFont(font)
        self.label_state_device.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_state_device.setStyleSheet("background: none;")
        self.label_state_device.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_state_device.setObjectName("label_state_device")
        self.label_last_sync = QtWidgets.QLabel(self.centralwidget)
        self.label_last_sync.setGeometry(QtCore.QRect(20, 658, 631, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_last_sync.setFont(font)
        self.label_last_sync.setStyleSheet("background: none;")
        self.label_last_sync.setObjectName("label_last_sync")
        self.label_sync_state = QtWidgets.QLabel(self.centralwidget)
        self.label_sync_state.setGeometry(QtCore.QRect(20, 523, 761, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_sync_state.setFont(font)
        self.label_sync_state.setStyleSheet("background: none;")
        self.label_sync_state.setObjectName("label_sync_state")
        self.label_current_name = QtWidgets.QLabel(self.centralwidget)
        self.label_current_name.setGeometry(QtCore.QRect(22, 17, 561, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_current_name.setFont(font)
        self.label_current_name.setStyleSheet("background: none;")
        self.label_current_name.setObjectName("label_current_name")
        self.buttonicon_logout = QtWidgets.QToolButton(self.centralwidget)
        self.buttonicon_logout.setGeometry(QtCore.QRect(640, 12, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.buttonicon_logout.setFont(font)
        self.buttonicon_logout.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.buttonicon_logout.setStyleSheet("QToolButton {\n"
"background-color: transparent;\n"
"border: none;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"background-color: rgba(255, 255, 255, 0.4);\n"
"}")
        self.buttonicon_logout.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("src/ui/qt-designer/../medias/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonicon_logout.setIcon(icon2)
        self.buttonicon_logout.setIconSize(QtCore.QSize(24, 24))
        self.buttonicon_logout.setObjectName("buttonicon_logout")
        self.progressbar_sync = QtWidgets.QProgressBar(self.centralwidget)
        self.progressbar_sync.setGeometry(QtCore.QRect(20, 559, 761, 31))
        self.progressbar_sync.setStyleSheet("QProgressBar {\n"
"color: white;\n"
"    font-size: 15px;\n"
"    text-align: center;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    background-color: #000000;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border-radius: 5px;\n"
"    background-color: #8D80AD; \n"
"}")
        self.progressbar_sync.setProperty("value", 100)
        self.progressbar_sync.setObjectName("progressbar_sync")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 57, 801, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 482, 801, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 640, 801, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.buttonicon_switch_account = QtWidgets.QToolButton(self.centralwidget)
        self.buttonicon_switch_account.setGeometry(QtCore.QRect(590, 13, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.buttonicon_switch_account.setFont(font)
        self.buttonicon_switch_account.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.buttonicon_switch_account.setStyleSheet("QToolButton {\n"
"background-color: transparent;\n"
"border: none;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"background-color: rgba(255, 255, 255, 0.4);\n"
"}")
        self.buttonicon_switch_account.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("src/ui/qt-designer/../medias/switch_account.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonicon_switch_account.setIcon(icon3)
        self.buttonicon_switch_account.setIconSize(QtCore.QSize(24, 24))
        self.buttonicon_switch_account.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.buttonicon_switch_account.setObjectName("buttonicon_switch_account")
        self.buttonicon_refresh = QtWidgets.QToolButton(self.centralwidget)
        self.buttonicon_refresh.setGeometry(QtCore.QRect(21, 440, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonicon_refresh.setFont(font)
        self.buttonicon_refresh.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.buttonicon_refresh.setStyleSheet("QToolButton {\n"
"background-color: transparent;\n"
"border: none;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"background-color: rgba(255, 255, 255, 0.2);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("src/ui/qt-designer/../medias/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonicon_refresh.setIcon(icon4)
        self.buttonicon_refresh.setIconSize(QtCore.QSize(24, 24))
        self.buttonicon_refresh.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.buttonicon_refresh.setObjectName("buttonicon_refresh")
        self.label_device_infos = QtWidgets.QLabel(self.centralwidget)
        self.label_device_infos.setGeometry(QtCore.QRect(390, 86, 391, 371))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_device_infos.setFont(font)
        self.label_device_infos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_device_infos.setObjectName("label_device_infos")
        main_window.setCentralWidget(self.centralwidget)
        self.actionParameters = QtWidgets.QAction(main_window)
        font = QtGui.QFont()
        self.actionParameters.setFont(font)
        self.actionParameters.setObjectName("actionParameters")
        self.actionAbout = QtWidgets.QAction(main_window)
        font = QtGui.QFont()
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Foxync"))
        self.buttonicon_options.setToolTip(_translate("main_window", "Settings"))
        self.buttonicon_options.setText(_translate("main_window", "⚙️"))
        self.buttonicon_about.setToolTip(_translate("main_window", "About"))
        self.buttonicon_about.setText(_translate("main_window", "?"))
        self.label_state_device.setText(_translate("main_window", "<html><head/><body><p> <span style=\" font-weight:600; color:#1fb614;\">Online</span></p></body></html>"))
        self.label_last_sync.setText(_translate("main_window", "<html><head/><body><p>Last synchronization : <span style=\" font-weight:600;\">2024/04/22 10:42</span></p></body></html>"))
        self.label_sync_state.setText(_translate("main_window", "Synchronized"))
        self.label_current_name.setText(_translate("main_window", "<html><head/><body><p>Connected as <span style=\" font-weight:600;\">[name] </span>on <span style=\" font-weight:600;\">[device]</span></p></body></html>"))
        self.buttonicon_logout.setToolTip(_translate("main_window", "Log out"))
        self.buttonicon_switch_account.setToolTip(_translate("main_window", "Switch profile"))
        self.buttonicon_refresh.setToolTip(_translate("main_window", "Refresh informations"))
        self.buttonicon_refresh.setText(_translate("main_window", "  Refresh"))
        self.label_device_infos.setText(_translate("main_window", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Name : </span><span style=\" font-size:14pt;\"><br/></span></p><p><span style=\" font-size:14pt; font-weight:600;\">MAC :</span><span style=\" font-size:14pt;\"><br/></span></p><p><span style=\" font-size:14pt; font-weight:600;\">IP : </span><span style=\" font-size:14pt;\"><br/></span></p><p><span style=\" font-size:14pt; font-weight:600;\">Status : </span><span style=\" font-size:14pt;\"><br/></span></p><p><span style=\" font-size:14pt; font-weight:600;\">Last sync. :</span></p></body></html>"))
        self.actionParameters.setText(_translate("main_window", "Parameters"))
        self.actionAbout.setText(_translate("main_window", "About"))
