# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/qt-designer/foxync_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_popup_window(object):
    def setupUi(self, popup_window):
        popup_window.setObjectName("popup_window")
        popup_window.resize(600, 150)
        self.label = QtWidgets.QLabel(popup_window)
        self.label.setGeometry(QtCore.QRect(0, 0, 601, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.button1 = QtWidgets.QPushButton(popup_window)
        self.button1.setGeometry(QtCore.QRect(165, 100, 130, 34))
        self.button1.setObjectName("button1")
        self.button2 = QtWidgets.QPushButton(popup_window)
        self.button2.setGeometry(QtCore.QRect(305, 100, 130, 34))
        self.button2.setObjectName("button2")

        self.retranslateUi(popup_window)
        QtCore.QMetaObject.connectSlotsByName(popup_window)

    def retranslateUi(self, popup_window):
        _translate = QtCore.QCoreApplication.translate
        popup_window.setWindowTitle(_translate("popup_window", "Changes"))
        self.label.setText(_translate("popup_window", "<html><head/><body><p align=\"center\">This device contains changes that are not synchronized. Would you like </p><p align=\"center\">to apply the local changes to other connected devices or overwrite the local files ?</p></body></html>"))
        self.button1.setText(_translate("popup_window", "Transfert changes"))
        self.button2.setText(_translate("popup_window", "Overwrite"))
