# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/qt-designer/foxync_signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signup_window(object):
    def setupUi(self, signup_window):
        signup_window.setObjectName("signup_window")
        signup_window.resize(350, 425)
        self.button_create = QtWidgets.QPushButton(signup_window)
        self.button_create.setGeometry(QtCore.QRect(24, 330, 300, 34))
        self.button_create.setObjectName("button_create")
        self.textbox_username = QtWidgets.QLineEdit(signup_window)
        self.textbox_username.setGeometry(QtCore.QRect(24, 140, 300, 32))
        self.textbox_username.setMaxLength(150)
        self.textbox_username.setClearButtonEnabled(True)
        self.textbox_username.setObjectName("textbox_username")
        self.textbox_password = QtWidgets.QLineEdit(signup_window)
        self.textbox_password.setGeometry(QtCore.QRect(24, 180, 300, 32))
        self.textbox_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.textbox_password.setClearButtonEnabled(True)
        self.textbox_password.setObjectName("textbox_password")
        self.label = QtWidgets.QLabel(signup_window)
        self.label.setGeometry(QtCore.QRect(150, 40, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Estrangelo Edessa")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(signup_window)
        self.label_4.setGeometry(QtCore.QRect(68, 20, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("src/ui/qt-designer/../medias/logo-foxync_no_background.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.textbox_confirm_password = QtWidgets.QLineEdit(signup_window)
        self.textbox_confirm_password.setGeometry(QtCore.QRect(24, 220, 300, 32))
        self.textbox_confirm_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.textbox_confirm_password.setClearButtonEnabled(True)
        self.textbox_confirm_password.setObjectName("textbox_confirm_password")
        self.label_wrong = QtWidgets.QLabel(signup_window)
        self.label_wrong.setEnabled(True)
        self.label_wrong.setGeometry(QtCore.QRect(26, 116, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_wrong.setFont(font)
        self.label_wrong.setStyleSheet("color: red;")
        self.label_wrong.setWordWrap(False)
        self.label_wrong.setObjectName("label_wrong")
        self.button_login = QtWidgets.QPushButton(signup_window)
        self.button_login.setGeometry(QtCore.QRect(24, 370, 300, 34))
        self.button_login.setObjectName("button_login")

        self.retranslateUi(signup_window)
        QtCore.QMetaObject.connectSlotsByName(signup_window)
        signup_window.setTabOrder(self.textbox_username, self.textbox_password)
        signup_window.setTabOrder(self.textbox_password, self.textbox_confirm_password)
        signup_window.setTabOrder(self.textbox_confirm_password, self.button_create)
        signup_window.setTabOrder(self.button_create, self.button_login)

    def retranslateUi(self, signup_window):
        _translate = QtCore.QCoreApplication.translate
        signup_window.setWindowTitle(_translate("signup_window", "Create an account"))
        self.button_create.setText(_translate("signup_window", "Create account"))
        self.textbox_username.setPlaceholderText(_translate("signup_window", "Username"))
        self.textbox_password.setPlaceholderText(_translate("signup_window", "Password"))
        self.label.setText(_translate("signup_window", "FOXYNC"))
        self.textbox_confirm_password.setPlaceholderText(_translate("signup_window", "Confirm password"))
        self.label_wrong.setText(_translate("signup_window", "Password must have at least 6 characters"))
        self.button_login.setText(_translate("signup_window", "Return to log in page"))
